# Google App Engine configuration for Digital Raksha
runtime: python311

# Environment variables
env_variables:
  VIRUSTOTAL_API_KEY: ""
  BLOCK_THRESHOLD: "4.0"
  SCAN_CACHE_TTL: "300"

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Health checks
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Skip files
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?venv/.*$
  - ^(.*/)?venv_new/.*$
  - ^(.*/)?venv_fresh/.*$
  - ^(.*/)?frontend/.*$
  - ^(.*/)?__pycache__/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.gitignore$
  - ^(.*/)?README\.md$
  - ^(.*/)?DEPLOYMENT_CHECKLIST\.md$
