services:
  - type: web
    name: digital-raksha-backend
    env: python
    plan: free
    pythonVersion: "3.10.13"
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
