name: Deploy to Google App Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import detector; print('Detector module loaded successfully')"
        python -c "import server; print('Server module loaded successfully')"
    
    - name: Deploy to Google App Engine
      if: github.ref == 'refs/heads/main'
      uses: google-github-actions/deploy-appengine@v1
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        deliverables: app.yaml
